// 構造 sync ticket 的 prompt(把 base branch 的更新拉進 pipeline worktree)。
// sub-agent 在 worktree 內操作(用 git -C "<worktreePath>"),不動 main repo。
// 重要:不能用 inline backtick(踩過兩次),所有 inline code 用單引號或不框。

export function syncTicketPrompt(opts: {
  worktreePath: string;
  branch: string;
  baseBranch: string;
  behindCount: number;
}): string {
  const { worktreePath, branch, baseBranch, behindCount } = opts;
  return [
    "AI sync 任務。把 base '" + baseBranch + "' 的最新內容 merge 進 pipeline worktree(branch '" + branch + "')。",
    "目前落後 " + behindCount + " 個 commit。",
    "",
    "**所有 git 操作都用 git -C \"" + worktreePath + "\" 顯式指定 worktree,不切 cwd**。",
    "(你的 cwd 已經是 worktree,但仍用 -C 顯式指定,避免歧義。)",
    "",
    "## 流程",
    "",
    "1. 預檢:",
    "   - Bash: git -C \"" + worktreePath + "\" status --porcelain → 確認 worktree 乾淨(沒未 commit 改動)",
    "   - **不乾淨 → 用 FAIL_NORETRY 開頭報告**(reason='worktree 不乾淨,前一張 ticket 沒收尾'),這是不會自動好的條件,iter 不該重試",
    "   - Bash: git -C \"" + worktreePath + "\" rev-parse --verify " + baseBranch + " → base branch 存在",
    "   - branch 不存在 → FAIL_NORETRY + reason='base branch 不存在'",
    "",
    "2. merge:",
    "   - Bash: git -C \"" + worktreePath + "\" merge --no-ff " + baseBranch + " --no-commit (先 merge 不 commit;見下方 commit 規則)",
    "   - 若 git 直接回 'Already up to date' → 沒事可做,直接 PASS(reason='nothing to sync',MERGE_COMMIT_HASH 不用)",
    "",
    "3. 衝突處理(merge 出現 CONFLICT):",
    "   - Bash: git -C \"" + worktreePath + "\" diff --name-only --diff-filter=U → 列出衝突檔",
    "   - 對每個衝突檔(用絕對路徑 \"" + worktreePath + "/<相對路徑>\"):",
    "     a. Read 看內容(<<<<<<< / ======= / >>>>>>> markers)",
    "     b. **branch side(<<<)是 pipeline 累積的成果,base side(>>>)是 base 上平行的修改**;保留 branch side 邏輯,融合 base side 的平行修改",
    "     c. Edit 解衝突,markers 全清掉",
    "     d. Bash: git -C \"" + worktreePath + "\" add <相對路徑>",
    "   - 全解完 → 進「## merge commit message」compose 後 commit",
    "   - 解不出來 → Bash: git -C \"" + worktreePath + "\" merge --abort,回報 FAIL + 衝突檔列表",
    "",
    "## merge commit message",
    "",
    "merge --no-ff 模式 worktree 上多一個 sync merge commit。訊息簡短:",
    "  - 第一行:'sync: merge " + baseBranch + " into " + branch + "'",
    "  - body(可選):一句話說 base 帶進來什麼(e.g., '帶入 base 上 phase 4 的 ticket-based AI merge 改動')",
    "Bash:",
    "  git -C \"" + worktreePath + "\" commit -m \"<subject>\" [-m \"<body>\"]",
    "",
    "4. 驗證:",
    "   - Bash: cat \"" + worktreePath + "/package.json\" 看有哪些 script",
    "   - 有 'build' → Bash: cd \"" + worktreePath + "\" && bun run build (timeout 5min)",
    "   - 有 'test' → Bash: cd \"" + worktreePath + "\" && bun run test (timeout 10min)",
    "   - 沒這些就跑 Bash: cd \"" + worktreePath + "\" && bunx tsc --noEmit",
    "   - 任一驗證 fail:",
    "     a. 試一次自動修復:Read 錯誤檔(絕對路徑),Edit 修,git -C \"" + worktreePath + "\" add + git -C \"" + worktreePath + "\" commit --amend --no-edit",
    "     b. 第二次還 fail → 不 reset,回報失敗 + 錯誤摘要",
    "",
    "5. 收尾(成功):",
    "   - Bash: git -C \"" + worktreePath + "\" rev-parse HEAD → 抓 syncCommit hash",
    "   - 回應開頭明確寫:'PASS\\nSYNC_COMMIT_HASH=<hash>' 或(已最新)'PASS\\nNOTHING_TO_SYNC'",
    "",
    "失敗 → 在回應開頭明確寫一種:",
    "  - 'FAIL\\n<reason 一行>' — 可重試的失敗(衝突解錯、驗證 fail 等)。runner 會 iter 再給一次",
    "  - 'FAIL_NORETRY\\n<reason 一行>' — 條件不會自動改善的失敗(worktree 髒、branch 不存在等)。runner 看到立刻終止 iter",
    "",
    "## 不踩",
    "",
    "- 不要切 cwd 出 worktree,所有 git 操作都針對 \"" + worktreePath + "\"(這條 worktree)。",
    "- **不要動 main repo**(target project 路徑),sync 只在 worktree 內 merge base 進來。",
    "- 不要 git pull / fetch / push / reset --hard / rebase。全 local。",
    "- 解衝突時 markers 必須完全清掉。",
    "- 一輪驗證沒過自動修一次就好,不要無限迴圈。",
    "",
    "## acceptance(critic 會檢查)",
    "",
    "- worktree 上 HEAD 包含 " + baseBranch + " 的最新 commit(rev-list --count " + baseBranch + " ^HEAD = 0)",
    "- worktree 乾淨(沒未 commit 的 conflict markers)",
    "- 驗證(tsc / build / test)PASS",
  ].join("\n");
}
